In [2]:
# Import the cugraph modules
import cugraph
import cudf
from cugraph.datasets import karate

# import the non-Rapids required modules
import numpy as np
import pandas as pd   
from IPython.display import display_html

In [31]:
# Compute Centrality
# the centrality calls are very straightforward with the graph being the primary argument
# we are using the default argument values for all centrality functions

def compute_centrality(_graph) :
    # Compute Degree Centrality
    _d = cugraph.degree_centrality(_graph)
        
    # Compute the Betweenness Centrality
    _b = cugraph.betweenness_centrality(_graph)

    # Compute Katz Centrality
    _k = cugraph.katz_centrality(_graph)

    # Compute PageRank Centrality
    _p = cugraph.pagerank(_graph)

    # Compute EigenVector Centrality
    _e = cugraph.eigenvector_centrality(_graph, max_iter=1000, tol=1.0e-3)
    
    return _d, _b, _k, _p, _e
    # return _d, _b

In [29]:
# Print function
def print_centrality(k,dc,bc,katz,pr, ev):

    dc_top = dc.sort_values(by='degree_centrality', ascending=False).head(k).to_pandas()
    bc_top = bc.sort_values(by='betweenness_centrality', ascending=False).head(k).to_pandas()
    katz_top = katz.sort_values(by='katz_centrality', ascending=False).head(k).to_pandas()
    pr_top = pr.sort_values(by='pagerank', ascending=False).head(k).to_pandas()
    ev_top = ev.sort_values(by='eigenvector_centrality', ascending=False).head(k).to_pandas()
    
    df1_styler = dc_top.style.set_table_attributes("style='display:inline'").set_caption('Degree').hide(axis='index')
    df2_styler = bc_top.style.set_table_attributes("style='display:inline'").set_caption('Betweenness').hide(axis='index')
    df3_styler = katz_top.style.set_table_attributes("style='display:inline'").set_caption('Katz').hide(axis='index')
    df4_styler = pr_top.style.set_table_attributes("style='display:inline'").set_caption('PageRank').hide(axis='index')
    df5_styler = ev_top.style.set_table_attributes("style='display:inline'").set_caption('EigenVector').hide(axis='index')

    display_html(df1_styler._repr_html_()+df2_styler._repr_html_()+df3_styler._repr_html_()+df4_styler._repr_html_()+df5_styler._repr_html_(), raw=True)

# Print function
# def print_centrality(k,dc,bc):
# 
#     dc_top = dc.sort_values(by='degree_centrality', ascending=False).head(k).to_pandas()
#     bc_top = bc.sort_values(by='betweenness_centrality', ascending=False).head(k).to_pandas()
#     
#     df1_styler = dc_top.style.set_table_attributes("style='display:inline'").set_caption('Degree').hide(axis='index')
#     df2_styler = bc_top.style.set_table_attributes("style='display:inline'").set_caption('Betweenness').hide(axis='index')
# 
#     display_html(df1_styler._repr_html_()+df2_styler._repr_html_(), raw=True)

In [32]:
# Create a graph using the imported Dataset object

# Define the path to the test data
datafile='./_datasets/combined_dataset_sample_a_to_a_100.csv'

# gdf = cudf.read_csv(datafile, delimiter=',', names=['src', 'dst', 'wt'], dtype=['int32', 'int32', 'float'] )
gdf = cudf.read_csv(datafile, delimiter=',')
# gdf = cudf.read_csv(datafile, delimiter=',', names=['transaction_id', 'account_id', 'counterpart_id', 'month', 'amount'], dtype=['int32', 'int32', 'int32', 'int32', 'int32'] )

# create a Graph using the source (src) and destination (dst) vertex pairs from the Dataframe
# G = cugraph.MultiGraph(directed=True)
# G.from_cudf_edgelist(gdf, 
#                      source='account_id', 
#                      destination='counterpart_id',
#                      edge_attr=['transaction_id', 'month', 'amount'])
# dc, bc, katz, pr, ev = compute_centrality(G)
# print_centrality(100, dc, bc, katz, pr, ev)

# create a Graph using the source (src) and destination (dst) vertex pairs from the Dataframe 
G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='account_id', destination='counterpart_id')
dc, bc, katz, pr, ev = compute_centrality(G)
print_centrality(100, dc, bc, katz, pr, ev)

# dc, bc = compute_centrality(G)
# print_centrality(100, dc, bc)

/home/bigdyl/anaconda3/envs/iris/lib/python3.10/site-packages/cugraph/structure/symmetrize.py:93: FutureWarning: Multi is deprecated and the removal of multi edges will no longer be supported from 'symmetrize'. Multi edges will be removed upon creation of graph instance.
  warnings.warn(
/home/bigdyl/anaconda3/envs/iris/lib/python3.10/site-packages/cugraph/centrality/katz_centrality.py:121: UserWarning: Katz centrality expects the 'store_transposed' flag to be set to 'True' for optimal performance during the graph creation
  warnings.warn(warning_msg, UserWarning)
/home/bigdyl/anaconda3/envs/iris/lib/python3.10/site-packages/cugraph/link_analysis/pagerank.py:227: UserWarning: Pagerank expects the 'store_transposed' flag to be set to 'True' for optimal performance during the graph creation
  warnings.warn(warning_msg, UserWarning)
/home/bigdyl/anaconda3/envs/iris/lib/python3.10/site-packages/cugraph/centrality/eigenvector_centrality.py:88: UserWarning: Eigenvector centrality expects the 'store_transposed' flag to be set to 'True' for optimal performance during the graph creation
  warnings.warn(warning_msg, UserWarning)

degree_centrality,vertex
1.932203,1
0.033898,0
0.033898,41200
0.033898,299157
0.033898,303176
0.033898,304763
0.033898,307806
0.033898,308454
0.033898,325862
0.033898,329575
0.033898,329677
0.033898,331573
0.033898,333340
0.033898,335863
0.033898,336818
0.033898,339807
0.033898,347571
0.033898,387148
0.033898,448585
0.033898,453791
0.033898,463575
0.033898,476180
0.033898,556357
0.033898,559077
0.033898,559516
0.033898,571396
0.033898,577124
0.033898,582826
0.033898,632529
0.033898,649695
0.033898,653383
0.033898,657341
0.033898,676360
0.033898,679051
0.033898,679882
0.033898,684741
0.033898,708741
0.033898,711549
0.033898,713783
0.033898,854469
0.033898,911036
0.033898,961626
0.033898,976910
0.033898,979621
0.033898,981949
0.033898,982949
0.033898,984157
0.033898,997124
0.033898,997194
0.033898,1014811
0.033898,1022922
0.033898,1024782
0.033898,1030777
0.033898,1035311
0.033898,1045642
0.033898,1063158
0.033898,1067220
0.033898,1068361
0.033898,1088058
0.033898,1136446
vertex,betweenness_centrality
1,0.932788
0,0.000000
41200,0.000000
299157,0.000000
303176,0.000000
304763,0.000000
307806,0.000000
308454,0.000000
325862,0.000000
329575,0.000000
329677,0.000000
331573,0.000000
333340,0.000000
335863,0.000000
336818,0.000000
339807,0.000000
347571,0.000000
387148,0.000000
448585,0.000000
453791,0.000000
463575,0.000000
476180,0.000000
556357,0.000000
559077,0.000000
559516,0.000000
571396,0.000000
577124,0.000000
582826,0.000000
632529,0.000000
649695,0.000000
653383,0.000000
657341,0.000000
676360,0.000000
679051,0.000000
679882,0.000000
684741,0.000000
708741,0.000000
711549,0.000000
713783,0.000000
854469,0.000000
911036,0.000000
961626,0.000000
976910,0.000000
979621,0.000000
981949,0.000000
982949,0.000000
984157,0.000000
997124,0.000000
997194,0.000000
1014811,0.000000
1022922,0.000000
1024782,0.000000
1030777,0.000000
1035311,0.000000
1045642,0.000000
1063158,0.000000
1067220,0.000000
1068361,0.000000
1088058,0.000000
1136446,0.000000
vertex,katz_centrality
1,0.190084
41200,0.127834
299157,0.127834
303176,0.127834
304763,0.127834
307806,0.127834
308454,0.127834
325862,0.127834
329575,0.127834
329677,0.127834
331573,0.127834
333340,0.127834
335863,0.127834
336818,0.127834
339807,0.127834
347571,0.127834
387148,0.127834
448585,0.127834
453791,0.127834
463575,0.127834
476180,0.127834
556357,0.127834
559077,0.127834
559516,0.127834
571396,0.127834
577124,0.127834
582826,0.127834
632529,0.127834
649695,0.127834
653383,0.127834
657341,0.127834
676360,0.127834
679051,0.127834
679882,0.127834
684741,0.127834
708741,0.127834
711549,0.127834
713783,0.127834
854469,0.127834
911036,0.127834
961626,0.127834
976910,0.127834
979621,0.127834
981949,0.127834
982949,0.127834
984157,0.127834
997124,0.127834
997194,0.127834
1022922,0.127834
1024782,0.127834
1030777,0.127834
1035311,0.127834
1045642,0.127834
1063158,0.127834
1067220,0.127834
1068361,0.127834
1088058,0.127834
1136446,0.127834
0,0.127283
1014811,0.127283
vertex,pagerank
1,0.445498
0,0.016667
1014811,0.016667
41200,0.009143
299157,0.009143
303176,0.009143
304763,0.009143
307806,0.009143
308454,0.009143
325862,0.009143
329575,0.009143
329677,0.009143
331573,0.009143
333340,0.009143
335863,0.009143
336818,0.009143
339807,0.009143
347571,0.009143
387148,0.009143
448585,0.009143
453791,0.009143
463575,0.009143
476180,0.009143
556357,0.009143
559077,0.009143
559516,0.009143
571396,0.009143
577124,0.009143
582826,0.009143
632529,0.009143
649695,0.009143
653383,0.009143
657341,0.009143
676360,0.009143
679051,0.009143
679882,0.009143
684741,0.009143
708741,0.009143
711549,0.009143
713783,0.009143
854469,0.009143
911036,0.009143
961626,0.009143
976910,0.009143
979621,0.009143
981949,0.009143
982949,0.009143
984157,0.009143
997124,0.009143
997194,0.009143
1022922,0.009143
1024782,0.009143
1030777,0.009143
1035311,0.009143
1045642,0.009143
1063158,0.009143
1067220,0.009143
1068361,0.009143
1088058,0.009143
1136446,0.009143
vertex,eigenvector_centrality
1,0.704476
41200,0.094006
299157,0.094006
303176,0.094006
304763,0.094006
307806,0.094006
308454,0.094006
325862,0.094006
329575,0.094006
329677,0.094006
331573,0.094006
333340,0.094006
335863,0.094006
336818,0.094006
339807,0.094006
347571,0.094006
387148,0.094006
448585,0.094006
453791,0.094006
463575,0.094006
476180,0.094006
556357,0.094006
559077,0.094006
559516,0.094006
571396,0.094006
577124,0.094006
582826,0.094006
632529,0.094006
649695,0.094006
653383,0.094006
657341,0.094006
676360,0.094006
679051,0.094006
679882,0.094006
684741,0.094006
708741,0.094006
711549,0.094006
713783,0.094006
854469,0.094006
911036,0.094006
961626,0.094006
976910,0.094006
979621,0.094006
981949,0.094006
982949,0.094006
984157,0.094006
997124,0.094006
997194,0.094006
1022922,0.094006
1024782,0.094006
1030777,0.094006
1035311,0.094006
1045642,0.094006
1063158,0.094006
1067220,0.094006
1068361,0.094006
1088058,0.094006
1136446,0.094006
0,0.000000
1014811,0.000000